gocd_trigger_api_url_ssm_param_name="/registrations/prod/user-input/dashboard-gocd-api-url"
gocd_trigger_api_token_ssm_param_name="/registrations/prod/user-input/dashboard-gocd-api-token"
data_pipeline_private_subnet_id_param_name="/registrations/prod/data-pipeline/base-networking/private-subnet-id"
data_pipeline_outbound_only_security_group_id_param_name="/registrations/prod/data-pipeline/base-networking/outbound-only-security-group-id"
gocd_subnet_id_param_name="/registrations/prod/user-input/gocd-subnet-id"
gocd_outbound_security_group_id_param_name="/registrations/prod/data-pipeline/base-networking/gocd-vpc-outbound-only-security-group-id"