reports_generator_repo_param_name="/registrations/dev/data-pipeline/ecr/url/reports-generator"
log_group_param_name="/registrations/dev/data-pipeline/cloudwatch-log-group-name"
execution_role_arn_param_name="/registrations/dev/data-pipeline/ecs-execution-role-arn"
transfers_input_bucket_param_name="/registrations/dev/data-pipeline/transfer-classifier/output-bucket-name"
transfer_input_bucket_read_access_param_name="/registrations/dev/data-pipeline/transfer-classifier/output-bucket-read-access-arn"
notebook_data_bucket_name="prm-gp2gp-notebook-data-dev"