transfer_classifier_repo_param_name="/registrations/preprod/data-pipeline/ecr/url/transfer-classifier"
execution_role_arn_param_name="/registrations/preprod/data-pipeline/ecs-execution-role-arn"
spine_messages_bucket_param_name="/registrations/preprod/data-pipeline/spine-exporter/output-bucket-name"
log_group_param_name="/registrations/preprod/data-pipeline/cloudwatch-log-group-name"
notebook_data_bucket_name="prm-gp2gp-notebook-data-prod"
ods_metadata_bucket_read_access_arn="/registrations/preprod/data-pipeline/ods-downloader/output-bucket-read-access-arn"