platform_metrics_calculator_repo_param_name="/registrations/dev/data-pipeline/ecr/url/platform-metrics-calculator"
log_group_param_name="/registrations/dev/data-pipeline/cloudwatch-log-group-name"
execution_role_arn_param_name="/registrations/dev/data-pipeline/ecs-execution-role-arn"
spine_messages_input_bucket_param_name="/registrations/dev/data-pipeline/spine-exporter/output-bucket-name"
ods_metadata_input_bucket_param_name="/registrations/dev/data-pipeline/ods-downloader/output-bucket-name"