format_version: 4
pipelines:
  "data-pipeline-container-repositories":
    group: gp2gp-data-pipeline-infra
    label_template: "${container_repositories[:8]}"
    materials:
      container_repositories:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-pipeline-infra.git
          path: stacks/container-repositories
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate container-repositories dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/container-repositories/terraform/dev.tfplan
                    destination: stacks/container-repositories/terraform
                - build:
                    source: stacks/container-repositories/terraform/.terraform.lock.hcl
                    destination: stacks/container-repositories/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan container-repositories dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/container-repositories/terraform/dev.tfplan
                    destination: stacks/container-repositories/terraform
                    is_file: yes
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/container-repositories/terraform/.terraform.lock.hcl
                    destination: stacks/container-repositories/terraform
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply container-repositories dev
      - validate_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            plan:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate container-repositories prod
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/container-repositories/terraform/prod.tfplan
                    destination: stacks/container-repositories/terraform
                - build:
                    source: stacks/container-repositories/terraform/.terraform.lock.hcl
                    destination: stacks/container-repositories/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan container-repositories prod
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/container-repositories/terraform/prod.tfplan
                    destination: stacks/container-repositories/terraform
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/container-repositories/terraform/.terraform.lock.hcl
                    destination: stacks/container-repositories/terraform
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply container-repositories prod
