format_version: 4
pipelines:
  "prm-gp2gp-data-ecs-cluster-infra":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        includes:
          - stacks/ecs-cluster/**/*
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate ecs-cluster dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan ecs-cluster dev