format_version: 4
pipelines:
  "data-pipeline-metrics-calculator-task":
    group: gp2gp-data-pipeline-infra
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        includes:
          - stacks/metrics-calculator/**/*
          - stacks/step-function/**/*
          - gocd/metrics-calculator.pipeline.gocd.yaml
      metrics_calculator_image:
        pipeline: prm-gp2gp-data-pipeline
        stage: build_and_publish
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate metrics-calculator dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_metrics_calculator_image_tag=$GO_DEPENDENCY_LABEL_METRICS_CALCULATOR_IMAGE ./tasks dojo-plan metrics-calculator dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: dev.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply metrics-calculator dev
      - promote_to_preprod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./scripts/promote-image dev preprod metrics-calculator $GO_DEPENDENCY_LABEL_METRICS_CALCULATOR_IMAGE
      - plan_preprod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: preprod.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan metrics-calculator preprod
      - apply_preprod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_preprod
                    job: plan
                    source: preprod.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply metrics-calculator preprod
