format_version: 4
pipelines:
  "data-pipeline-metrics-calculator-task":
    group: gp2gp-data-pipeline-infra
    label_template: "${metrics_calculator_task[:8]}"
    materials:
      metrics_calculator_task:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-pipeline-infra.git
          path: stacks/metrics-calculator
      metrics_calculator_image:
        pipeline: prm-gp2gp-metrics-calculator
        stage: build_and_publish
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate metrics-calculator dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_metrics_calculator_image_tag=$GO_DEPENDENCY_LABEL_METRICS_CALCULATOR_IMAGE ./tasks dojo-plan metrics-calculator dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: dev.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply metrics-calculator dev
      - promote_to_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./scripts/promote-image dev prod metrics-calculator $GO_DEPENDENCY_LABEL_METRICS_CALCULATOR_IMAGE
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: prod.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_metrics_calculator_image_tag=$GO_DEPENDENCY_LABEL_METRICS_CALCULATOR_IMAGE ./tasks dojo-plan metrics-calculator prod
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: prod.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply metrics-calculator prod
