format_version: 4
pipelines:
  "data-pipeline-ods-downloader-task":
    group: gp2gp-data-pipeline-infra
    label_template: "${ods_downloader_task[:8]}"
    materials:
      ods_downloader_task:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-pipeline-infra.git
          path: stacks/ods-downloader
      ods_downloader_image:
        pipeline: prm-gp2gp-ods-downloader
        stage: build_ods_downloader
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate ods-downloader dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_ods_downloader_image_tag=$GO_DEPENDENCY_LABEL_ODS_DOWNLOADER_IMAGE ./tasks dojo-plan ods-downloader dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: dev.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply ods-downloader dev
      - promote_to_preprod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./scripts/promote-image dev preprod ods-downloader $GO_DEPENDENCY_LABEL_ODS_DOWNLOADER_IMAGE
      - plan_preprod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: preprod.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_ods_downloader_image_tag=$GO_DEPENDENCY_LABEL_ODS_DOWNLOADER_IMAGE ./tasks dojo-plan ods-downloader preprod
      - apply_preprod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_preprod
                    job: plan
                    source: preprod.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply ods-downloader preprod
