format_version: 4
pipelines:
  "data-pipeline-ods-downloader-infra":
    group: gp2gp-data-pipeline-infra
    label_template: "${git[:8]}"
    materials:
      container_repositories:
        pipeline: data-pipeline-container-repositories
        stage: apply_dev
      git:
        type: configrepo
        includes:
          - stacks/ods-downloader/**/*
      ods_downloader_image:
        pipeline: prm-gp2gp-ods-downloader
        stage: build_ods_downloader
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate ods-downloader dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_image_id=$GO_DEPENDENCY_LABEL_ODS_DOWNLOADER_IMAGE ./tasks dojo-plan ods-downloader dev