format_version: 4
pipelines:
  "prm-gp2gp-data-pipeline-infra":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - echo hellodev
      - apply_prod:
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          apply:
            resources:
              - docker
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - echo helloprod
