format_version: 4
pipelines:
  "data-pipeline-reports-generator-task":
    group: gp2gp-data-pipeline-infra
    label_template: "${reports_generator_task[:8]}"
    materials:
      reports_generator_task:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-pipeline-infra.git
          path: stacks/reports-generator
      reports_generator_image:
        pipeline: prm-gp2gp-reports-generator
        stage: build_and_publish
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate reports-generator dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/reports-generator/terraform/dev.tfplan
                    destination: stacks/reports-generator/terraform
                - build:
                    source: stacks/reports-generator/terraform/.terraform.lock.hcl
                    destination: stacks/reports-generator/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_reports_generator_image_tag=$GO_DEPENDENCY_LABEL_REPORTS_GENERATOR_IMAGE ./tasks dojo-plan reports-generator dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/reports-generator/terraform/dev.tfplan
                    destination: stacks/reports-generator/terraform
                    is_file: yes
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/reports-generator/terraform/.terraform.lock.hcl
                    destination: stacks/reports-generator/terraform
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply reports-generator dev
      - promote_to_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./scripts/promote-image dev prod reports-generator $GO_DEPENDENCY_LABEL_REPORTS_GENERATOR_IMAGE
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/reports-generator/terraform/prod.tfplan
                    destination: stacks/reports-generator/terraform
                - build:
                    source: stacks/reports-generator/terraform/.terraform.lock.hcl
                    destination: stacks/reports-generator/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_reports_generator_image_tag=$GO_DEPENDENCY_LABEL_REPORTS_GENERATOR_IMAGE ./tasks dojo-plan reports-generator prod
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/reports-generator/terraform/prod.tfplan
                    destination: stacks/reports-generator/terraform
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/reports-generator/terraform/.terraform.lock.hcl
                    destination: stacks/reports-generator/terraform
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply reports-generator prod
