format_version: 4
pipelines:
  "data-pipeline-spine-exporter-task":
    group: gp2gp-data-pipeline-infra
    label_template: "${spine_exporter_task[:8]}"
    materials:
      spine_exporter_task:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-pipeline-infra.git
          path: stacks/spine-exporter
      spine_exporter_image:
        pipeline: prm-spine-exporter
        stage: build_and_publish
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate spine-exporter dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/spine-exporter/terraform/dev.tfplan
                    destination: stacks/spine-exporter/terraform
                - build:
                    source: stacks/spine-exporter/terraform/.terraform.lock.hcl
                    destination: stacks/spine-exporter/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_spine_exporter_image_tag=$GO_DEPENDENCY_LABEL_SPINE_EXPORTER_IMAGE ./tasks dojo-plan spine-exporter dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/spine-exporter/terraform/dev.tfplan
                    destination: stacks/spine-exporter/terraform
                    is_file: yes
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/spine-exporter/terraform/.terraform.lock.hcl
                    destination: stacks/spine-exporter/terraform
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply spine-exporter dev
      - promote_to_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./scripts/promote-image dev prod spine-exporter $GO_DEPENDENCY_LABEL_SPINE_EXPORTER_IMAGE
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/spine-exporter/terraform/prod.tfplan
                    destination: stacks/spine-exporter/terraform
                - build:
                    source: stacks/spine-exporter/terraform/.terraform.lock.hcl
                    destination: stacks/spine-exporter/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - TF_VAR_spine_exporter_image_tag=$GO_DEPENDENCY_LABEL_SPINE_EXPORTER_IMAGE ./tasks dojo-plan spine-exporter prod
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/spine-exporter/terraform/prod.tfplan
                    destination: stacks/spine-exporter/terraform
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/spine-exporter/terraform/.terraform.lock.hcl
                    destination: stacks/spine-exporter/terraform
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply spine-exporter prod
