format_version: 4
pipelines:
  "data-pipeline-validate-metrics":
    group: gp2gp-data-pipeline-infra
    label_template: "${validate_metrics[:8]}"
    materials:
      validate_metrics:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-pipeline-infra.git
          path: stacks/validate-metrics, lambda/validate-metrics
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate validate-metrics dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
                - build:
                    source: lambda/build/validate-metrics.zip
                    destination: lambda/build/
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan validate-metrics dev
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: dev.tfplan
                    is_file: yes
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: lambda/build/validate-metrics.zip
                    destination: lambda/build/
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply validate-metrics dev
      - validate_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            plan:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate validate-metrics prod
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: prod.tfplan
                - build:
                    source: lambda/build/validate-metrics.zip
                    destination: lambda/build/
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan validate-metrics prod
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: prod.tfplan
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: lambda/build/validate-metrics.zip
                    destination: lambda/build/
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply validate-metrics prod
