metrics_calculator_repo_param_name="/registrations/preprod/data-pipeline/ecr/url/metrics-calculator"
log_group_param_name="/registrations/preprod/data-pipeline/cloudwatch-log-group-name"
execution_role_arn_param_name="/registrations/preprod/data-pipeline/ecs-execution-role-arn"
transfers_input_bucket_param_name="/registrations/preprod/data-pipeline/transfer-classifier/output-bucket-name"
ods_metadata_input_bucket_param_name="/registrations/preprod/data-pipeline/ods-downloader/output-bucket-name"