name: Base Infrastructure Plan and Apply
on:
  push:
      branches: [ main ]
      paths:
        - 'stacks/container-repositories/**'
        - 'stacks/base-support/**'
        - 'stacks/base-networking/**'
        - 'stacks/ecs-cluster/**'
        - '.github/workflows/base-infrastructure-plan-and-apply.yml'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'stacks/container-repositories/**'
      - 'stacks/base-support/**'
      - 'stacks/base-networking/**'
      - 'stacks/ecs-cluster/**'
      - '.github/workflows/base-infrastructure-plan-and-apply.yml'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform_plan:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        environment: [ dev ]
        terraform_stack: [container-repositories, base-support, base-networking, ecs-cluster]
    uses: ./.github/workflows/base-terraform-plan-and-apply.yml
    with:
      environment: ${{ matrix.environment }}
      terraform_stack: ${{ matrix.terraform_stack }}
    secrets: inherit


