name: Build and Deploy Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'stacks/**'
      - '.github/workflows/**'
      - 'tasks_github_actions.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'stacks/**'
      - '.github/workflows/**'
      - 'tasks_github_actions.sh'

jobs:
  base-infrastructure:
    uses: ./.github/workflows/base-infrastructure.yml

  data-pipeline:
    needs: base-infrastructure
    uses: ./.github/workflows/data-pipeline.yml

  email-and-alerting:
    needs: data-pipeline
    uses: ./.github/workflows/email-and-alerting.yml

  build-lambdas:
    needs: email-and-alerting
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
          mask-aws-account-id: true

      - name: Build Lambda Functions
        run: |
          chmod +x ./tasks_github_actions.sh
          ./tasks_github_actions.sh build-lambdas 