name: Deploy Degrades

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - 'lambda/degrades_dashboards/**'
      - 'stacks/degrades_dashboards/**'
      - '.github/workflows/deploy-degrades.yml'

  pull_request:
    branches: [ main ]
    paths:
      - 'lambda/degrades_dashboards/**'
      - 'stacks/degrades_dashboards/**'
      - '.github/workflows/deploy-degrades.yml'


permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo Hello World

  deploy_degrades_infra:
    uses: ./.github/workflows/base-terraform-plan-and-apply.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: degrades_dashboards
      build_lambda: true
    secrets: inherit