name: Deploy Degrades

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - '../../lambda/degrades-dashboards/**'
      - 'stacks/degrades-dashboards/**'
      - '.github/workflows/deploy-degrades.yml'

  pull_request:
    branches: [ main ]
    paths:
      - '../../lambda/degrades-dashboards/**'
      - 'stacks/degrades-dashboards/**'
      - '.github/workflows/deploy-degrades.yml'


permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  test_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Test Lambda
        working-directory: lambda/degrades-dashboards
        run: |
          pip install pytest
          pytest tests/


  deploy_degrades_infra:
    uses: ./.github/workflows/base-terraform-plan-and-apply.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: degrades-dashboards
      build_lambda: true
    secrets: inherit