name: Destroy select infrastructure stack

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        description: Stack to destroy
        options:
          - degrades-dashboards
        required: true
      environment:
        description: Environment of stack to destroy
        default: "dev"
        required: true
      terraform_vars:
        default: 'dev.tfvars'
        description: 'Terraform vars file to use.'
        required: true

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  destroy_stack:
    if: inputs.environment == 'dev'
    defaults:
      run:
        working-directory: ./stacks/${{ inputs.stack }}/terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

# this might not be needed, think the runner has pip built in.
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build Lambda Zip
        run: |
          cd $GITHUB_WORKSPACE 
          rm -rf lambda/build/${{ inputs.stack }} 
          mkdir -p lambda/build/${{ inputs.stack }} 
          pip install -r lambda/${{ inputs.stack }}/requirements.txt -t lambda/build/${{ inputs.stack }} 
          cp lambda/${{ inputs.stack }}/*.py lambda/build/${{ inputs.stack }} 
          
          pushd lambda/build/${{ inputs.stack }} 
          zip -r -X ../${{ inputs.stack }}.zip . 
          popd

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          mask-aws-account-id: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'

      - name: Terraform Init
        run: |
          terraform init -no-color -backend-config="key=data-pipeline/${{ inputs.stack }}/terraform.tfstate" \
          -backend-config="bucket=${{ secrets.AWS_STATE_BUCKET }}" \
          -backend-config="dynamodb_table=${{ secrets.AWS_STATE_LOCK_TABLE }}"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -var-file="../vars/${{ inputs.terraform_vars }}" -var "environment=dev"
