name: Email and  Alerting Plan and Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'stacks/email-and-alerting/**'
      - 'stacks/gp2gp-dashboard/**'
      - '.github/workflows/email-and-alerting-plan-and-apply.yml'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'stacks/email-and-alerting/**'
      - 'stacks/gp2gp-dashboard/**'
      - '.github/workflows/email-and-alerting-plan-and-apply.yml'

jobs:
  email-and-alerting:
    uses: ./.github/workflows/base-terraform-plan-and-apply.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: email-and-alerting
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_ROLE_ARN_READ_ONLY: ${{ secrets.AWS_ROLE_ARN_READ_ONLY }}
      STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
      STATE_LOCK_TABLE: ${{ secrets.STATE_LOCK_TABLE }}

  gp2gp-dashboard:
    needs: email-and-alerting
    uses: ./.github/workflows/base-terraform-plan-and-apply.yml
    with:
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      terraform_stack: gp2gp-dashboard
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_ROLE_ARN_READ_ONLY: ${{ secrets.AWS_ROLE_ARN_READ_ONLY }}
      STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
      STATE_LOCK_TABLE: ${{ secrets.STATE_LOCK_TABLE }}