name: Lambdas Plan and Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'lambdas/**'
      - '.github/workflows/email-and-alerting.yml'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'lambdas/**'
      - '.github/workflows/email-and-alerting.yml'

jobs:
    build-lambdas:
        runs-on: ubuntu-latest
        environment: dev
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Build Lambda Functions
            run: |
                chmod +x ./tasks_github_actions.sh
                ./tasks_github_actions.sh build-lambdas
        
