name: Reusable Lambda Build
on:
  workflow_dispatch:
    inputs:
      lambda:
        default: ""
        type: string
        description: Lambda directory needed to be built
  workflow_call:
    inputs:
      lambda:
        description: Lambda directory needed to be built
        default: ""
        type: string

permissions:
  pull-requests: write
  id-token: write
  contents: read


jobs:
  build_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build Lambda Zip
        run: |
          cd $GITHUB_WORKSPACE 
          rm -rf lambda/build/${{ inputs.lambda }} 
          mkdir -p lambda/build/${{ inputs.lambda }} 
          pip install -r lambda/${{ inputs.lambda }}/requirements.txt -t lambda/build/${{ inputs.lambda }} 
          rsync -av --progress lambda/${{ inputs.lambda }} lambda/build/${{ inputs.lambda }} --exclude tests
          
          pushd lambda/build/${{ inputs.lambda }} 
          zip -r -X ../${{ inputs.lambda }}.zip . 
          popd
